#!/usr/bin/env bash
# Function to handle SIGTERM signal
sigterm_handler() {
    echo "I hate the kill command"
}

# Function to handle SIGINT signal
sigint_handler() {
    echo "Y U no love me?!"
}

# Function to handle SIGQUIT signal
sigquit_handler() {
    sudo rm -f /var/run/myscript.pid
    exit 0
}

# Trap signals and call appropriate functions
trap 'sigterm_handler' SIGTERM
trap 'sigint_handler' SIGINT
trap 'sigquit_handler' SIGQUIT

# Save PID to file
sudo sh -c 'echo $$ > /var/run/myscript.pid'

# Loop indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done
