#!/usr/bin/env bash
#  a Bash script that displays to infinity and beyond indefinitely
# Define a function to handle SIGTERM signal
sigterm_handler()
{
	echo "I am invincible!!!"
	exit 0
}
trap sigterm_handler SIGTERM
while true;
do
	echo "To infinity and beyond"
	sleep 2
done
