#!/usr/bin/env bash
#  a Bash script that displays the content of the file /etc/passwd,
# using the while loop + IFS
while IFS=':' read -r username password uid gid gecos home shell;
do
	user_info=$(grep "^$username:" /etc/passwd | cut -d ":" -f 5)
	uid_info=$(grep "^$uid:" /etc/passwd | cut -d ":" -f 5)
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
	echo "User ID's place is protected by the passcode $password, more info about the user here: $uid_info"
done < /etc/passwd
