#!/usr/bin/env bash
# a Bash script that displays the content of the current directory
# Where only the part of the name after the first dash is displayed
for file in *;
do
	if [[ ! "$file" =~ ^\. && -f "$file" ]]; then
		name=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name"
	fi
done
